config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  root              'static_pages#home'

  get 'help'    =>  'static_pages#help'

  get 'about'   =>  'static_pages#about'

  get 'contact' =>  'static_pages#contact'

  get 'signup'  =>  'users#new'

  get 'login'   =>  'sessions#new'
  post 'login'  =>  'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users

  resources :account_activations, only: [:edit]

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :remember_token, :activation_token

  #before_save { self.email = email.downcase }
  #Ch6 exerc 2: this method can be written using the bang! method:
  #before_save { email.downcase! }
  #ch 10 change block to a 'method reference'
  before_save :downcase_email
  before_create :create_activation_digest

  validates :name, presence: true, length: { maximum: 50 }

  #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i Replaced by regex
  # which detects ..com format errors:
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:true,
            length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            #  uniqueness: true changed to: [implicating true]:
            uniqueness: { case_sensitive: false}

  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true

  #Added in ch8.2.4 : adding a digest method for use in fixtures
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  #ch8.4 Remember token [with attribute accessor and remember method]
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end


private
    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController

  def edit
    @user=User.find_by(email: params[:email])
    if user && user.authenticated?(:activation, params[:id])
  #  @user = User.find(params[:id]) #why not: show @user
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      #created after including SessionHelper in AppController, and def log_in method
      log_in user
      #puts "I am here (sessionsController#create)" instead of adding 'raise'
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      #redirect_to user
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid combination'

      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #adding in 9.2.1 : only logged in user can edit, update, with def logged_in_user below
before_action :logged_in_user,  only: [:index, :edit, :update, :destroy]
  #adding in 9.2.2
before_action :correct_user,    only: [:edit, :update]
before_action :admin_user,      only: :destroy



  def index
  #  @users = User.all
  @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    #µd: with debugger in action, go to terminal to use it.
    #debugger
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      #added in ch8.2.5 :
      #changed in ch10.21
      #log_in @user

      #Adding redirect following signup form submission
      #redirect_to user_url(@user) is in short:
      #flash[:success] = "Welcome to Mauds Rails App :-) "
      #redirect_to @user
      UserMailer.account_activation(@user).deliver_now
      flash[:info] = "Check your email to activate your account"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
  #  @user = User.find(params[:id]) #why not: show @user
  end

  def update
  #  @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Your profile is updated :-) "
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:succes] = "User deleted"
    redirect_to users_url
  end


  private

    def user_params
      params.require(:user).permit(:name, :email,
                                 :password, :password_confirmation )
                                 #, :admin ) #added for exercise 9.3
    end

    #before filters

    def logged_in_user
      unless logged_in?
        store_location   #added in 9.28
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      #redirect_to(root_url) unless @user == current_user
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Mauds Rails App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    #this session method is a Rails method. It places a temp cookie which expires upon closing the browser
    session[:user_id] = user.id
  end

  #added in ch8.4
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  #adding in listing 9.24. (returns true if the given user is the correct user)
  #Not sure if this is right? :
  def current_user?(user)
    user == current_user
  end


  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])

      #extra test uit listing 8.53
      #raise
      # my way:
      #puts "I was here def current user"
      user = User.find_by(id: user_id)

      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  #added in 9.27
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  #returns the Gravatar for given user (ch7)
  def gravatar_for(user, options = { size:80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",  root_path %></li>
        <li><%= link_to "Help",   help_path %></li>

        <% if logged_in? %>
          <li> <%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class= "dropdown-toggle" data-toggle="dropdown">
              Account <b class = "caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>

      </ul>

    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>


    <%= render 'layouts/shim' %>

  </head>
  <body>

    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <!--<div class="alert alert-<%= message_type %>"><%= message %> </div>
        replaced with cleaner code: -->
      <%= content_tag(:div, message, class: "alert altert-#{message_type}") %>
      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>
      <!-- adding in ch 7, using the built in debug method to add debug info
      to homepage (with layout in css-file): -->
      <%= debug(params) if Rails.env.development? %>

    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<!-- adding in ch 7 Shared dir for partials showing error_messages, available in different views -->

<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class = "alert alert_danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

    <h1>About</h1>
    <p>This is about it...
    </p>

app/views/static_pages/aboutVB.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>About | Mauds Rails App</title>

    </head>
  <body>

    <h1>About</h1>
    <p>This is about it...
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>


    <h1>Contact</h1>
    <p>Please keep in touch <a href="mailto:maud@charta.nl?Subject=InTouch">by email</a>
    </p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>


    <h1>Help wanted</h1>
    <p>Need help? Forget it!
    </p>
  

app/views/static_pages/home.html.erb
<div class="center jumbotron">


    <h1>Welkom home</h1>
    <p> Good to see you here or at <a href="http://www.charta.nl">Charta</a>
    </p>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    </div>

    <%= link_to image_tag("rails.png", alt: "Rails logo"),
                'http://rubyonrails.org/' %>

app/views/users/_fields.html.erb
    <%= render 'shared/error_messages' %>

      <!-- Adding form-control from bootstrap -->
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

    

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    <%= link_to "Delete", user, method: :delete,
    data: { confirm: "Are you sure?" } %>
    <% end %>

</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit profile') %>

<h1>Update your profile</h1>

 <div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>

      <%= f.submit "Update my account", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatoar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target=_blank>change</a>
    </div>
 </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<h1>All users</h1>

<%= will_paginate %>


<ul class="users">


<!-- refactored in 9.4 , to _user.html.erb, then call render directly on @users-->
  <%= render @users %>

</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>

 <div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>

      <%= render 'fields', f: f %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>